version: '3'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: s3cr3tp4ssw0rd
      MYSQL_DATABASE: ps
    ports:
      - 3306:3306
  app:
    depends_on:
      - db
    build: .
    command: ["./wait-for-it.sh", "db:3306", "--", "./add-functions.sh"]
    volumes:
      - .:/opt/public-suffix
    links:
      - db